### ISSUE TITLE
Request: add Bing

### ISSUE THREAD

**Issue by yokoffing** [quenhus/uBlock-Origin-dev-filter#374]
We have Ecosia and Brave, but not Bing? I anticipate more users using Bing since they're slowly launching their AI.

**Comment by quenhus** [comment]
Hi, sorry for the late response.
You are right, it would be nice to support Bing.

I start looking at it and there is an issue: On desktop, Bing is statically replacing the real URL with a click tracking link. 

To block bad results, we need to use this filter: `bing.com###b_results cite:has-text("qastack.fr"):upward(.b_algo)`.

This filter uses `has-text()` and I don't think it will have great performance. Anyone has a better idea?

**Comment by xvello** [comment]
Heya @quenhus, I looked into it and could not find a better way to implement in with uBO. That's why we'll be [removing Bing support from letsblock.it](https://github.com/iorate/ublacklist) instead of changing it to `has-text()`.

We should redirect people to https://github.com/iorate/ublacklist instead, that can run this filtering more efficiently, by amortizing the URL extraction cost over the whole website list, instead of repeatedly doing it.

You could consider publishing the dataset as an ublacklist subscription [[see documentation]](https://iorate.github.io/ublacklist/docs/advanced-features#publish-a-subscription).

**Comment by quenhus** [comment]
Hi,

Thanks a lot @xvello. Indeed, I recommend [uBlacklist](https://github.com/iorate/ublacklist) to remove bad domains from Bing results.

All my filters are already fully compatible with uBlacklist. I recommend to activate the option "Add rules blocking whole sites by default" to block all subdomains.

Links for uBlacklist subscription:

- [github_copycats](https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/data/github_copycats.txt)
- [wikipedia_copycats](https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/data/wikipedia_copycats.txt)
- [stackoverflow_copycats](https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/data/stackoverflow_copycats.txt)
- [npm_copycats](https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/data/npm_copycats.txt)
- [seo_spam](https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/data/seo_spam.txt)
