### ISSUE TITLE
Request: add more hn clones to the filter

### ISSUE THREAD

**Issue by AndrewKvalheim** [quenhus/uBlock-Origin-dev-filter#380]
Evidence:

  - https://hacker-news-vue.mturco.com/story/34010112
  - https://hn.kyoto.codes/story/34010112
  - https://hn.matthewblode.com/item/34010112
  - https://hn.nuxt.space/item/34010112
  - https://hn.premii.com/#/comments/34010112
  - https://hn.svelte.dev/item/34010112
  - https://modernorange.io/item/34010112

Original: https://news.ycombinator.com/item?id=34010112

**Comment by quenhus** [comment]
Thanks a lot for your contribution.

I'm quite embarrassed with these ones. HN has a such antique front-end, I can understand people developing modern front-end.

A lot of these domains are demonstrations made by designer. `hn.svelte.dev` is even made as an official demo to `svelte`, a famous JS framework.

What is your opinion?

**Comment by quenhus** [comment]
To me, HN mirrors are not as annoying as StackOverflow mirrors, because you don't often look for a response on HN from search engine.

One might query `How to parse date in Python` and dislike having multiple copies of response. I can't think of a similar situation with HN (one without being able to add `site:news.ycombinator.com` is the query).

**Comment by AndrewKvalheim** [comment]
Agreed. The motive in creating these sites is different; the QA clones appear intended to mislead but these are personal projects and tech demos.

Personally I wouldn’t recommend blocking these but after encountering #370 I thought that was a goal of this project.

**Comment by realAzazello** [comment]
> Agreed...these are personal projects and tech demos.
> 
> Personally I wouldn’t recommend blocking these.

Just wanted to add, I agree--https://github.com/quenhus/uBlock-Origin-dev-filter/issues/370 can be reverted to also `not-planned'.

But as stated, when do we know when clones are pet or love projects - or SEO or trolls? It's a slippery slope, but I don't have a good answer

**Comment by quenhus** [comment]
Hi,
Thanks a lot for your contribution.

> It's a slippery slope trying to manually and subjectively evaluate them. 

I agree with you, the selection is subjective. 

However, in this case, I find that the reference to Hackernews is almost non-existent. There is not link or attribution to the original content.

What do you think?

**Comment by realAzazello** [comment]
And thank-you! quenhus, you're the G.O.A.T. in the community.

> However, in this case, I find that the reference to Hackernews is almost non-existent. There is not link or attribution to the original content.
> 
> What do you think?

It's still a toughy because if it's just a lul project, the creator might not make an effort to attribute or reference.

My opinion is... because 'he' put his name in the domain, this is a 'legit' project. Taking that jump, please revert.
