### ISSUE TITLE
Request: add accordeonmuseum.nl to the filter

### ISSUE THREAD

**Issue by ashemedai** [quenhus/uBlock-Origin-dev-filter#386]
Evidence: https://accordeonmuseum.nl/Zettelkasten
Original: https://en.wikipedia.org/wiki/Zettelkasten

Looks like they are applying an automatic translation step in-between as well. You can see various English remnants in the subsequent text.

Also, if you go to the root of the domain, they're not even hiding the fact that are a weird mirror of Wikipedia articles, featuring a similar frontend.

**Comment by quenhus** [comment]
Thanks a lot!

**Comment by nightkr** [comment]
Strange. Since october it seems to have been replaced with an.. actual accordeon museum's website, straight out of the early 00s (https://web.archive.org/web/20231001160526/https://accordeonmuseum.nl/). In fact, it looks *identical* to the state of the site between [2011](https://web.archive.org/web/20110513025945/http://www.accordeonmuseum.nl/) and [2000](https://web.archive.org/web/20000605053111/http://www.accordeonmuseum.nl:80/). However, in 2012 it was replaced with [first a redesign at a different domain](https://web.archive.org/web/20121028185209/http://www.demuse.nl/nl/museum/het%2Dmuseum/) and then [a different one in 2013 at yet another domain](https://web.archive.org/web/20140223155954/http://www.accordeonmuseum.com/dm/home/wat-is-de-muse/) (I'm assuming these are the same/affiliated since they share the name De Muse, the address of Kerkplein 12, and refer to Henk Kuik in some capacity). That site (.com) seems to have disappeared somewhere between 2021-2022, and been replaced by a placeholder.

**Comment by ashemedai** [comment]
@nightkr Could have been a site/domain takeover. From a quick look at the current site it seems harmless now.

@quenhus Unblock again?

Also makes me wonder how we should periodically check/verify domains on the list. 🤔
