### ISSUE TITLE
Search result filter not working for DuckDuckGo

### ISSUE THREAD

**Issue by metametapod** [quenhus/uBlock-Origin-dev-filter#390]
Same behavior as #89, looks like DDG updated their page structure again. This rule seems to work:

```
duckduckgo.com##.react-results--main>li:has(a[href*="copycatsite.com"])
```

**Comment by xvello** [comment]
Indeed, we fixed it in letsblock.it with https://github.com/letsblockit/letsblockit/pull/476, feel free to reuse that rule.
The image results are unchanged for now, it's only impacting text results.

**Comment by quenhus** [comment]
Hi !

I wanted to make sure that it was not AB testing and that it also works on mobile. Your proposition works perfectly, thanks a lot!

@xvello, I don't know if I ever asked you, but do you know which of `:has()` or `:upward()` has better performance in this case? [The doc](https://github.com/gorhill/uBlock/wiki/Filter-Performance#upward-vs-has) is not really clear to me.

In the selector, I would prefer filter on the `<li>` because otherwise it leaves a tiny margin. For now, I'm going with `duckduckgo.com##.react-results--main>li:has(a[href*="bad.example"])`
