### ISSUE TITLE
"Add this filter" button links to AdBlock Plus, not uBlock Origin

### ISSUE THREAD

**Issue by tylerlaprade** [quenhus/uBlock-Origin-dev-filter#403]
If I have AdBlock Plus or AdBlock installed, it adds the filter for those. If I don't, it does nothing. Is there a way to do a magic link for uBlock Origin, or does it require manual setup?

**Comment by quenhus** [comment]
Hi!

In my opinion, one should not use AdBlock or AdBlock Plus. These projets are [receiving money from advertisements companies](https://adblockplus.org/fr/about#monetization) to allow some ads.

Moreover, AdBlock doesn't support [strict website blocking](https://github.com/gorhill/uBlock/wiki/Strict-blocking), and only blocks secondary resources. That's why this filter is not compatible with AdBlock.

I won't make this filter more compatible with Adblock. However cosmetic filters on search engine results might work with AdBlock, but I didn't checked. 

You can install uBlock here : https://github.com/gorhill/uBlock and then use any filter from this projet.

**Comment by tylerlaprade** [comment]
@quenhus, I agree, I also prefer uBlock Origin. The links in the README should therefore be updated to be uBlock Origin links, not AdBlock Plus.
![image](https://github.com/quenhus/uBlock-Origin-dev-filter/assets/5475199/94cdcdd6-edf0-4ef5-b458-7c7d2ff75251)

**Comment by quenhus** [comment]
To create filter subscriptions in uBO you have two options: with `ubo://` protocol or with `https://subscribe.adblockplus.org` (see https://github.com/gorhill/uBlock/blob/1ff3878a4920e31791547238e3e879a32357914f/src/js/scriptlets/subscriber.js#L58)

On Github, you can't create link with `ubo://`, so I use the second method with `https://subscribe.adblockplus.org`

**Comment by tylerlaprade** [comment]
I see, thank you!
