### ISSUE TITLE
"Not a valid filter list" in ABP

### ISSUE THREAD

**Issue by tylerlaprade** [quenhus/uBlock-Origin-dev-filter#404]
When I click the magic links in `README.md` with AdBlock Plus installed, they autocreate invalid filters in ABP:
![image](https://github.com/quenhus/uBlock-Origin-dev-filter/assets/5475199/9e39fb39-387a-4f97-8baa-f9475ce09029)

**Comment by quenhus** [comment]
Hi!

In my opinion, one should not use AdBlock or AdBlock Plus. These projets are [receiving money from advertisements companies](https://adblockplus.org/fr/about#monetization) to allow some ads.

Moreover, AdBlock doesn't support [strict website blocking](https://github.com/gorhill/uBlock/wiki/Strict-blocking), and only blocks secondary resources. That's why this filter is not compatible with AdBlock.

I won't make this filter more compatible with Adblock. However cosmetic filters on search engine results might work with AdBlock, but I didn't checked.

You can install uBlock here : https://github.com/gorhill/uBlock and then use any filter from this projet.
